### PR TITLE
Add Fedora details

### PR DESCRIPTION
**Pull request by bexelbie**

### CODE REVIEW

**Comment by rfjakob** [comment]
Very nice, thank you!

**Comment by rfjakob** [comment]
Published to https://nuetzlich.net/gocryptfs/quickstart/

**Comment by LicoMonch** [comment]
@rfjakob @bexelbie 
the new instructions lack information about the package "fuse", which is not a dep for the gocryptfs-fedora-package and must be installed manually

**Comment by bexelbie** [comment]
@LicoMonch Thank you for catching this - my test systems must have all had fuse installed.  I've fixed the requires, I think.  Rawhide should update shortly and f30 is in bodhi here:

https://bodhi.fedoraproject.org/updates/FEDORA-2019-fd0a1f6908

Your karma is appreciated!

**Comment by LicoMonch** [comment]
@bexelbie 
yep, works now: fuse is pulled in as a dep on installation

**Comment by FranklinYu** [comment]
@bexelbie Hi, I cannot seem to find the package in https://apps.fedoraproject.org/packages. Is there any step before I `sudo dnf install gocryptfs`?

**Comment by bexelbie** [comment]
@franklinyu there are no special requirements. It is only built for Fedora 30 and 31. 31 is the auto rebuild I haven’t had a chance to personally upgrade and test it yet. 

I’m not sure why it isn’t listed. I’ll look into it.

**Pull request merged**
